- name: Install required packages
  action: apt pkg={{ item }} state=installed
  with_items:
    - git
    - python-pip
    - python-dev
    - supervisor
    - cmake
    - libusb-1.0-0-dev
    - libhamlib-utils
    - vorbis-tools

- name: Blacklist dvb_usb_rtl28xxu module
  kernel_blacklist: name=dvb_usb_rtl28xxu state=present

- name: Disable dvb_usb_rtl28xxu module
  modprobe: name=dvb_usb_rtl28xxu state=absent

- name: Fetch SatNOGS rtl-sdr fork
  git: repo=https://github.com/satnogs/rtl-sdr.git dest=/root/rtl-sdr
  register: rtl_sdr_repository

- name: Create rtl-sdr build directory
  file: state=directory path=/root/rtl-sdr/build

- name: Build rtl-sdr
  command: "{{ item }} chdir=/root/rtl-sdr/build"
  with_items:
    - cmake ..
    - make
  when: rtl_sdr_repository.changed

- name: Install rtl-sdr
  command: make install chdir=/root/rtl-sdr/build
  when: rtl_sdr_repository.changed

- name: Update latest shared libraries
  command: ldconfig
  when: rtl_sdr_repository.changed

- name: Copy udev rules
  command: cp /root/rtl-sdr/rtl-sdr.rules /etc/udev/rules.d
  when: rtl_sdr_repository.changed

- name: Update udev rules
  command: udevadm trigger
  when: rtl_sdr_repository.changed

- name: Install satnogs-client
  pip: name=satnogsclient
  notify:
    - Restart satnogs

- name: Setup supervisor for rotctld process
  template: src="supervisor-rotctld.conf.j2" dest="/etc/supervisor/conf.d/rotctld.conf"
  notify:
    - Restart rotctld

- name: Setup supervisor for satnogs-poller process
  template: src="supervisor-satnogs-poller.conf.j2" dest="/etc/supervisor/conf.d/satnogs.conf"
  notify:
    - Restart satnogs
